/**
 * JWT Types and Enums for Production-Grade Token Management
 * Aligned with financial services security standards
 */

/**
 * User Role Enum - Strongly typed roles for access control
 */
export enum UserRole {
  CLIENT = 'CLIENT',
  ANALYST = 'ANALYST',
  ADMIN = 'ADMIN',
}

/**
 * JWT Standard Claims with Role
 * Payload structure for access and refresh tokens
 */
export interface JwtPayload {
  /** Subject - Unique identifier (replaces clientId) */
  sub: string;
  
  /** Email address of the user */
  email: string;
  
  /** User role - Required for all authenticated users */
  role: UserRole;
  
  /** JWT ID - Unique identifier for this specific token (for revocation tracking) */
  jti: string;
  
  /** Issuer - Identifies the principal that issued the JWT */
  iss: string;
  
  /** Audience - Identifies the recipients that the JWT is intended for */
  aud: string;
  
  /** Issued At - Generated by jsonwebtoken library (ISO 8601 or seconds) */
  iat?: number;
  
  /** Expiration Time - Generated by jsonwebtoken library via expiresIn */
  exp?: number;
  
  /** Algorithm - Always RS256 for asymmetric signing */
  alg?: string;
}

/**
 * Verified JWT Payload after successful verification
 * Guarantees that signature, exp, and algorithm have been validated
 */
export interface VerifiedJwtPayload extends JwtPayload {
  /** Guaranteed to exist after verification */
  sub: string;
  email: string;
  role: UserRole;
  jti: string;
  exp: number;
  iat: number;
}

/**
 * Decoded JWT Payload (unverified, for debugging only)
 * IMPORTANT: Never use for security decisions
 */
export interface DecodedJwtPayload extends Partial<JwtPayload> {}

/**
 * Token generation request payload
 * Omits iat, exp, and jti which are generated by the service
 */
export interface GenerateTokenPayload {
  sub: string;
  email: string;
  role: UserRole;
}

/**
 * Token pair response structure
 */
export interface TokenPair {
  accessToken: string;
  refreshToken: string;
  accessTokenExpiresIn: number;
  refreshTokenExpiresIn: number;
}

/**
 * Structured token error information
 */
export enum TokenErrorType {
  EXPIRED = 'EXPIRED',
  MALFORMED = 'MALFORMED',
  INVALID_SIGNATURE = 'INVALID_SIGNATURE',
  INVALID_ALGORITHM = 'INVALID_ALGORITHM',
  MISSING_CLAIMS = 'MISSING_CLAIMS',
  INVALID_CLAIMS = 'INVALID_CLAIMS',
  UNKNOWN = 'UNKNOWN',
}

/**
 * Structured token verification error
 */
export interface TokenVerificationError {
  type: TokenErrorType;
  message: string;
  timestamp: Date;
  tokenJti?: string; // Include JTI if available for tracking
}
